### ISSUE TITLE
Submit FileCase to SailfishOS:Chum

### ISSUE THREAD

**Issue by Olf0** [sailfishos-applications/filecase#28]
Steps:

0. Read the documentation: https://github.com/sailfishos-chum/main#sailfishoschum-community-repository
1. Get in touch with user **lbt** (David Greaves) to acquire an account for the SailfishOS OBS, via the IRC channel `#sailfishos` or a private message [at FSO](https://forum.sailfishos.org/).
2. Make FileCase build fine in your own OBS repo: It just takes a correctly configured `_service` file.
3. Then follow the aforementioned documentation.

@ruditimmermans, maybe this is something you could achieve. :slightly_smiling_face:
If you have any questions, do ask me here.

**Comment by ruditimmermans** [comment]
I will see what i can do in a few days i have some time to check this ;)

**Comment by ruditimmermans** [comment]
I have send today a message to David on the forum...

**Comment by ruditimmermans** [comment]
Till now no answher from David....

**Comment by Olf0** [comment]
Me, too (I have a different request to him).

**Comment by Olf0** [comment]
Done: https://build.sailfishos.org/request/show/3216
