### ISSUE TITLE
Donation link still working?

### ISSUE THREAD

**Issue by Olf0** [sailfishos-applications/filecase#61]
@CepiPerez, does [your original donation link](https://github.com/sailfishos-applications/filecase/blob/master/qml/pages/AboutPage.qml#L124) still work and do these donations still reach you via PayPal?
* If so, I plan to change the [donation link in FileCase's metadata for SailfishOS:Chum](https://github.com/sailfishos-applications/filecase/blob/master/rpm/filecase.spec#L88) to the original, aforementioned link.
* If not I would do exactly the opposite: Introduce OpenRepo's donation link in FileCase's `AboutPage.qml`.

Any thoughts, comments etc.?

P.S.: I just noticed, that while the PayPal link [in FlowPlayer's `About` page](https://github.com/sailfishos-applications/flowplayer/blob/devel/qml/pages/AboutPage.qml#L112) is the same as in FileCase's `About` page, the PayPal link on the OpenRepos pages for [FileCase](https://openrepos.net/content/cepiperez/filecase-0#content) and [FlowPlayer](https://openrepos.net/content/cepiperez/flowplayer-0#content) is a different one.  You may want to check if this other link also is still working and if not adapt these two OpenRepos pages accordingly.

**Comment by CepiPerez** [comment]
Hello. The link in qml page is the latest one. Openrepos link was for whatsup project

**Comment by Olf0** [comment]
Done by:
- PR #63
- FlowPlayer's [PR \#35](https://github.com/sailfishos-applications/flowplayer/pull/35)
- FileCase's [OpenRepos page](https://openrepos.net/content/olf/filecase#content)
- FlowPlayers's [OpenRepos page](https://openrepos.net/content/olf/flowplayer#content)
