### ISSUE TITLE
[Bug] `TS` files are not translated to `QM` files when building on OBS

### ISSUE THREAD

**Issue by ruditimmermans** [sailfishos-applications/filecase#68]
When choice into the lasted version on Chum the language to Dutch, and restart FileCase it keep seems to be into English, i have look in the translate directory on my Xperia 10 III and it seems empty, the lasted version on OpenRepos works fine.

**Comment by Olf0** [comment]
@ruditimmermans, please use the bug template next time.  By the language barrier and the relative information (e.g. "lasted") it is hard to comprehend what you specifically mean.

1. So, do I understand correctly, that the Dutch localisation works fine, when you install [FileCase 0.4.3](https://github.com/sailfishos-applications/filecase/releases/tag/rc4%2F0.4.3) from [OpenRepos](https://openrepos.net/content/olf/filecase) with an Xperia 10 III and the language set to Dutch in the SailfihsOS Settings app?
2. But there is no localisation (i.e. all strings are in English) when you install Filecase 0.4.3 from [SailfishOS:Chum](https://build.sailfishos.org/package/show/sailfishos:chum/FileCase) (still on the Xperia 10 III set to Dutch)?
3. Does `devel-su ls -l /usr/share/filecase/translations/` output only `total 0` in case 2, but shows the list of translation files in case 1?
4. In your PR #69 you write that after your code changes there, "*i have compile this with the sdk and translations would be there...*".  But the version at OpenRepos was also compiled with the SailfishOS-SDK (via Coderus' docker image at GitHub) and you wrote that it works for you.
   Have you compiled the original code from [`filecase-0.4.3.tar.gz`](https://github.com/sailfishos-applications/filecase/archive/refs/tags/rc4/0.4.3.tar.gz) or by checking out the git-tag `rc4/0.4.3` from [FileCase's repository at GitHub](https://github.com/sailfishos-applications/filecase.git] and checked if the Dutch localisation works and `/usr/share/filecase/translations/` is empty?

Please answer each of the questions 1 to 4 starting with a "Yes" or "No".  Actually you do not need to write more than that as each of the four answers, but feel free to write more.

Note that it is absolutely plausible that the software compiled by the SailfishOS-OBS (e.g. apps from SailfishOS:Chum) show different behaviour than the same source code compiled by the SailfishOS-SDK.  First of all I need to unambiguously comprehend your observations and statements.

Mind that `Settings`→`About` in Filecase 0.4.3-rc4 (= `filecase-0.4.3-1.1.1` at SailfishOS:Chum), 0.4.3-rc2 and 0.4.2-rc1 all display "Version 0.4.2", unfortunately (as you already seem to have discovered), but `pkcon search name filecase | fgrep installed` always shows you the real version number of the installed FileCase app.

**Comment by eson57** [comment]
1. Yes
2. Yes
3. Yes
4. I did not compile myself, but can tell that there are no translation files distributed from the Chum rpm (`/usr/share/filecase/translations/` is empty), but they are all there from OpenRepos.

**Comment by Olf0** [comment]
@eson57, sorry for having triggered your attention and requested a reply, this was a mishap.

@ruditimmermans, well if the original code compiled fine (i.e. emitting translation files) using the Sailfish-SDK, why do you believe that your "fix" (PR #69) is correct by testing with the Sailfish-SDK: Logically the translation files are there, as long as your "fix" did not break anything.

**Comment by Olf0** [comment]
After some testing where building the translation files fails (i.e. at the Sailfish-OBS), I conclude that [the error message has always been](https://build.sailfishos.org/package/live_build_log/sailfishos:chum:testing/FileCase/3.2.1.20_armv7hl/armv8el) (but nobody looked at it):
[  228s] lupdate: could not exec '/usr/lib/qt5/bin/lupdate': No such file or directory
[  228s] lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

Full log: [_log.txt](https://github.com/sailfishos-applications/filecase/files/14392725/_log.txt)

I suspect that something alike a `pkgconf(qt5i18n)` statement is missing in the spec file.  Must research further, but not today.

**Comment by Olf0** [comment]
### Generic Conclusion

If one when specifies `CONFIG += sailfishapp_i18n` in a Qt project (`.pro`) file (as [suggested by Jolla](https://sailfishos.org/develop/docs/libsailfishapp/#using-i18n-support-in-your-project)), one must specify `BuildRequires: qt5-qttools-linguist` in the spec file for such a project to successfully generate `.qm`-files on the Sailfish-OBS.
Otherwise no Qt i18n (`.qm`) files are generated from the translation (`.ts`) input files, because `lrelease` and `lupdate` are not installed in the build VM OBS spawns.
